// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCashRmk;

#nullable disable

namespace OnlineCashRmk.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineCashRmk.Models.Arrival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateArrival")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Num")
                        .HasColumnType("longtext");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.ArrivalGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArrivalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Count")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<string>("Nds")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("GoodId");

                    b.ToTable("ArrivalGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.BarCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.ToTable("BarCodes");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("SpecialPercent")
                        .HasColumnType("int");

                    b.Property<decimal>("SumBuy")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TemporyPercent")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CashMoney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TypeOperation")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("CashMoneys");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CheckSellId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Count")
                        .HasColumnType("double");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckSellId");

                    b.HasIndex("GoodId");

                    b.ToTable("CheckGoods", (string)null);
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CheckSellId")
                        .HasColumnType("int");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Retturn")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TypePayment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckSellId");

                    b.ToTable("CheckPayments");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckSell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsElectron")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumDiscont")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TypeSell")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ShiftId");

                    b.ToTable("CheckSells", (string)null);
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Creditor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumCredit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumDiscont")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("isSynch")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CreditGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Count")
                        .HasColumnType("double");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.HasIndex("GoodId");

                    b.ToTable("CreditGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CreditPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePayment")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditPayments");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamBirthdayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DayEnable")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TextSms")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamBirthdayModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamContainerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentFromSale")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("DiscountParamContainerModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamHolidaysModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHoliday")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TextSms")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamHolidaysModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamNumBuyerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumBuyer")
                        .HasColumnType("int");

                    b.Property<string>("TextSms")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamNumBuyerModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamSumBuyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("SumBuyesMore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamSumBuyModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamSumOneBuyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("SumBuy")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamSumOneBuyModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamWeeksModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .HasColumnType("longtext");

                    b.Property<int>("DayNum")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountParamContainerModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("TimeBy")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeWith")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DiscountParamContainerModelId");

                    b.ToTable("DiscountParamWeeksModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DiscountModelId")
                        .HasColumnType("int");

                    b.Property<string>("Discounts")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DiscountModelId");

                    b.ToTable("DiscountSettings");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DocSynch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Synch")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("SynchStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TypeDoc")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("DocSynches");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Article")
                        .HasColumnType("longtext");

                    b.Property<string>("BarCode")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SpecialType")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.Property<double?>("VPackage")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Goods", (string)null);
                });

            modelBuilder.Entity("OnlineCashRmk.Models.NewGoodFromCash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.ToTable("NewGoodsFromCash");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Revaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("Date");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Revaluations");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.RevaluationGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Count")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceNew")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PriceOld")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RevaluationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.HasIndex("RevaluationId");

                    b.ToTable("RevaluationGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CashierId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Stop")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumCredit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumElectron")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumIncome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumNoElectron")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumOutcome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SumSell")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SummReturn")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isSynch")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Stocktaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CashMoney")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isSynch")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Stocktakings");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.StocktakingGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("CountDocMove")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CountFact")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<int>("StocktakingGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.HasIndex("StocktakingGroupId");

                    b.ToTable("StocktakingGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.StocktakingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("StocktakingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StocktakingId");

                    b.ToTable("StocktakingGroups");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Inn")
                        .HasColumnType("longtext");

                    b.Property<string>("Kpp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Writeof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Writeofs");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.WriteofGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Count")
                        .HasColumnType("double");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("WriteofId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.HasIndex("WriteofId");

                    b.ToTable("WriteofGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Arrival", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Supplier", "Supplier")
                        .WithMany("Arrivals")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.ArrivalGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Arrival", "Arrival")
                        .WithMany("ArrivalGoods")
                        .HasForeignKey("ArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("ArrivalGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrival");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.BarCode", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("BarCodes")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.CheckSell", "CheckSell")
                        .WithMany("CheckGoods")
                        .HasForeignKey("CheckSellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("CheckGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckSell");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckPayment", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.CheckSell", "CheckSell")
                        .WithMany("CheckPayments")
                        .HasForeignKey("CheckSellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckSell");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckSell", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Buyer", "Buyer")
                        .WithMany("CheckSells")
                        .HasForeignKey("BuyerId");

                    b.HasOne("OnlineCashRmk.Models.Shift", "Shift")
                        .WithMany("CheckSells")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Credit", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Shift", "Shift")
                        .WithMany("Credits")
                        .HasForeignKey("ShiftId");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CreditGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Credit", "Credit")
                        .WithMany("CreditGoods")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CreditPayment", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Credit", "Credit")
                        .WithMany("CreditPayments")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamBirthdayModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("Birthdays")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamHolidaysModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("Holidays")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamNumBuyerModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("NumBuyer")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamSumBuyModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("SumBuys")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamSumOneBuyModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("SumOneBuys")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamWeeksModel", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", null)
                        .WithMany("Weeks")
                        .HasForeignKey("DiscountParamContainerModelId");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountSetting", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.DiscountParamContainerModel", "DiscountModel")
                        .WithMany()
                        .HasForeignKey("DiscountModelId");

                    b.Navigation("DiscountModel");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.NewGoodFromCash", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("NewGoodsFromCashe")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.RevaluationGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("RevaluationGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.Revaluation", "Revaluation")
                        .WithMany("RevaluationGoods")
                        .HasForeignKey("RevaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Revaluation");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.StocktakingGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("StocktakingGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.StocktakingGroup", "StocktakingGroup")
                        .WithMany("StocktakingGoods")
                        .HasForeignKey("StocktakingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("StocktakingGroup");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.StocktakingGroup", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Stocktaking", "Stocktaking")
                        .WithMany("StocktakingGroups")
                        .HasForeignKey("StocktakingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stocktaking");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.WriteofGood", b =>
                {
                    b.HasOne("OnlineCashRmk.Models.Good", "Good")
                        .WithMany("GetWriteofGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCashRmk.Models.Writeof", "Writeof")
                        .WithMany("WriteofGoods")
                        .HasForeignKey("WriteofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Writeof");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Arrival", b =>
                {
                    b.Navigation("ArrivalGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Buyer", b =>
                {
                    b.Navigation("CheckSells");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.CheckSell", b =>
                {
                    b.Navigation("CheckGoods");

                    b.Navigation("CheckPayments");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Credit", b =>
                {
                    b.Navigation("CreditGoods");

                    b.Navigation("CreditPayments");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.DiscountParamContainerModel", b =>
                {
                    b.Navigation("Birthdays");

                    b.Navigation("Holidays");

                    b.Navigation("NumBuyer");

                    b.Navigation("SumBuys");

                    b.Navigation("SumOneBuys");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Good", b =>
                {
                    b.Navigation("ArrivalGoods");

                    b.Navigation("BarCodes");

                    b.Navigation("CheckGoods");

                    b.Navigation("GetWriteofGoods");

                    b.Navigation("NewGoodsFromCashe");

                    b.Navigation("RevaluationGoods");

                    b.Navigation("StocktakingGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Revaluation", b =>
                {
                    b.Navigation("RevaluationGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Shift", b =>
                {
                    b.Navigation("CheckSells");

                    b.Navigation("Credits");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Stocktaking", b =>
                {
                    b.Navigation("StocktakingGroups");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.StocktakingGroup", b =>
                {
                    b.Navigation("StocktakingGoods");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Supplier", b =>
                {
                    b.Navigation("Arrivals");
                });

            modelBuilder.Entity("OnlineCashRmk.Models.Writeof", b =>
                {
                    b.Navigation("WriteofGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
